### PR TITLE
Added Alot

### PR DESCRIPTION
**Pull request by Boltovnya**
<3

### CODE REVIEW

**Comment by Gosha** [comment]
Cool. But that link forces an image download for me. Also the link is quite long. Mind rehosting it somewhere (pomf?) and updating this PR?

**Comment by Boltovnya** [comment]
Yeah, Of course

**Comment by Gosha** [comment]
Aww snap. I meant to merge to peabot branch

**Comment by Boltovnya** [comment]
God dammit, you can't do anything right

**Comment by Gosha** [comment]
;__;

**Pull request merged**
